/* YepFootball app.js: daily Latest Scores + live European Match Centre */
const leagues={all:{name:"All Europe",code:null},ucl:{name:"Champions League",code:"CL"},epl:{name:"Premier League",code:"PL"},laliga:{name:"La Liga",code:"PD"},seriea:{name:"Serie A",code:"SA"},bundesliga:{name:"Bundesliga",code:"BL1"},ligue1:{name:"Ligue 1",code:"FL1"}};
let selected="all",latestScoresData=null;const $=s=>document.querySelector(s);
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function fmtDate(v){try{return new Date(v).toLocaleString(undefined,{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}catch{return v}}
function fmtTime(v){try{return new Date(v).toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit"})}catch{return ""}}
async function getJSON(url){const r=await fetch(`${url}${url.includes("?")?"&":"?"}_=${Date.now()}`,{headers:{Accept:"application/json"},cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
function labels(){document.querySelectorAll('a[href="#scores"]').forEach(a=>a.textContent="Latest Scores");if($("#scores h2"))$("#scores h2").textContent="Latest Scores";if($("#scores .eyebrow"))$("#scores .eyebrow").textContent="DAILY RESULTS";const b=document.querySelector('.hero-actions a[href="#scores"]');if(b)b.textContent="See latest scores"}
function tabs(){const c=$("#league-tabs");if(!c)return;c.innerHTML=Object.entries(leagues).map(([k,v])=>`<button class="tab ${k===selected?"active":""}" data-league="${k}">${v.name}</button>`).join("");document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{selected=b.dataset.league;tabs();renderLatestScores(latestScoresData)})}
function team(t){return `<span class="team-name">${t?.crest?`<img class="team-crest" src="${esc(t.crest)}" alt="" loading="lazy">`:""}${esc(t?.shortName||t?.name||"Team")}</span>`}
function score(e,s){if(e.source==="API-Football")return s==="home"?(e.score?.home??"-"):(e.score?.away??"-");const f=e.score?.fullTime||{},r=e.score?.regularTime||{};return f[s]??r[s]??e.score?.current?.[s]??"-"}
function card(e){return `<article class="score-card"><div class="score-meta"><span>${esc(e.league||"Football")}</span><span>${esc(e.source==="API-Football"?(e.statusLong||e.status):e.status||"")}</span></div><div class="teams">${team(e.homeTeam)}<strong class="score">${score(e,"home")} — ${score(e,"away")}</strong>${team(e.awayTeam)}</div></article>`}
function fixture(e){return `<article class="fixture-card"><div class="fixture-date">${fmtDate(e.date)}</div><div class="fixture-teams">${team(e.homeTeam)}<span class="vs">vs</span>${team(e.awayTeam)}</div><div class="fixture-league">${esc(e.league||"European football")}</div></article>`}
function filter(a){const c=leagues[selected]?.code;return c?a.filter(e=>e.leagueCode===c):a}
function renderLatestScores(d){latestScoresData=d;const g=$("#scores-grid");if(!g)return;const a=filter(d?.events||[]);if(!a.length){g.innerHTML=`<div class="empty">No completed matches were recorded for ${esc(leagues[selected].name)}.<br><small>Daily results are published at 23:50 CET.</small></div>`;return}const dl=d.date?new Date(`${d.date}T12:00:00Z`).toLocaleDateString(undefined,{weekday:"long",day:"numeric",month:"long",year:"numeric"}):"Latest results";g.innerHTML=`<div class="score-group"><h3>FINAL SCORES · ${esc(dl)}</h3>${a.map(card).join("")}</div>`}
async function loadScores(){if($("#scores-status"))$("#scores-status").textContent="Loading…";try{const d=await getJSON("/api/scores");renderLatestScores(d);if($("#scores-status"))$("#scores-status").textContent=`${filter(d.events||[]).length} results · Published ${d.publishedAt?fmtTime(d.publishedAt):"23:50"}`;if($("#updated"))$("#updated").textContent=`Latest scores · ${d.date||""}`}catch(e){if($("#scores-grid"))$("#scores-grid").innerHTML=`<div class="empty">Latest scores are temporarily unavailable.</div>`;if($("#scores-status"))$("#scores-status").textContent="Feed unavailable";console.error(e)}}
function centreUI(){let c=$("#match-centre")||$("#matchCentre")||document.querySelector(".match-centre")||document.querySelector("[data-match-centre]");if(!c){const s=$("#scores")||$("#scores-grid")?.closest("section");if(!s?.parentNode)return null;c=document.createElement("section");c.id="match-centre";c.className="match-centre";c.innerHTML=`<div class="match-centre-header"><div><div class="match-centre-title">European Match Centre</div></div><div id="match-centre-status" class="match-centre-status">● LIVE DATA</div></div><div id="match-centre-content" class="match-centre-content"></div>`;s.parentNode.insertBefore(c,s)}return{content:c.querySelector("#match-centre-content,.match-centre-content"),status:c.querySelector("#match-centre-status,.match-centre-status")}}
function mcCard(e){return `<article class="match-centre-card ${e.live?"is-live":""}"><div class="match-centre-league">${esc(e.league)}</div><div class="match-centre-teams"><div class="match-centre-team">${team(e.homeTeam)}</div><div class="match-centre-score"><strong>${score(e,"home")} — ${score(e,"away")}</strong><span class="${e.live?"live":""}">${esc(e.minute?e.minute+"'":e.statusLong||e.status)}</span></div><div class="match-centre-team">${team(e.awayTeam)}</div></div></article>`}
async function loadMatchCentre(){const u=centreUI();if(!u)return;u.status.textContent="● CONNECTING…";try{const d=await getJSON("/api/match-centre"),a=d.events||[];u.content.innerHTML=a.length?a.slice(0,12).map(mcCard).join(""):`<div class="match-centre-empty">No European matches are live right now.<br><small>Live data connection is working.</small></div>`;u.status.textContent=d.liveCount?`● ${d.liveCount} LIVE`:"● LIVE DATA"}catch(e){u.status.textContent="● DATA UNAVAILABLE";u.content.innerHTML=`<div class="match-centre-empty">European Match Centre is temporarily unavailable.</div>`;console.error(e)}}
async function loadFixtures(){try{const d=await getJSON("/api/fixtures"),a=d.events||[];if($("#fixtures-grid"))$("#fixtures-grid").innerHTML=a.length?a.map(fixture).join(""):`<div class="empty">No upcoming fixtures found.</div>`}catch(e){if($("#fixtures-grid"))$("#fixtures-grid").innerHTML=`<div class="empty">Fixtures are temporarily unavailable.</div>`;console.error(e)}}
async function loadNews(){try{const d=await getJSON("/api/news"),a=d.articles||[];if($("#news-grid"))$("#news-grid").innerHTML=a.length?a.slice(0,9).map(n=>`<a class="news-card" href="${esc(n.link)}" target="_blank" rel="noopener">${n.image?`<img src="${esc(n.image)}" alt="" loading="lazy">`:""}<div><small>${esc(n.source||"Football news")}</small><h3>${esc(n.title)}</h3>${n.description?`<p>${esc(n.description)}</p>`:""}</div><span class="source">${n.published?fmtDate(n.published):"Latest"}</span></a>`).join(""):`<div class="empty">No news available right now.</div>`}catch(e){if($("#news-grid"))$("#news-grid").innerHTML=`<div class="empty">News feed is temporarily unavailable.</div>`;console.error(e)}}
document.addEventListener("DOMContentLoaded",()=>{labels();tabs();if($("#year"))$("#year").textContent=new Date().getFullYear();loadScores();loadMatchCentre();loadFixtures();loadNews();setInterval(loadMatchCentre,30000);setInterval(loadFixtures,900000);setInterval(loadNews,1800000)});
